import { LeaderboardUser, RankReward } from '@/types/user';

export const MOCK_LEADERBOARD: LeaderboardUser[] = [
  {
    id: '1',
    name: 'Trent',
    username: '@123t-cent',
    avatar: 'https://i.pravatar.cc/150?img=12',
    sustainabilityPoints: 3333,
    rank: 1,
    level: 5,
  },
  {
    id: '2',
    name: 'Chavers',
    username: '@kochavers',
    avatar: 'https://i.pravatar.cc/150?img=33',
    sustainabilityPoints: 2999,
    rank: 2,
    level: 2,
  },
  {
    id: '3',
    name: 'Alex Marie',
    username: '@masamarie',
    avatar: 'https://i.pravatar.cc/150?img=45',
    sustainabilityPoints: 2750,
    rank: 3,
    level: 3,
  },
  {
    id: '4',
    name: 'Melissa S.',
    username: '@melissas',
    avatar: 'https://i.pravatar.cc/150?img=5',
    sustainabilityPoints: 2636,
    rank: 4,
    level: 4,
  },
  {
    id: '5',
    name: 'Brian C.',
    username: '@brianc',
    avatar: 'https://i.pravatar.cc/150?img=13',
    sustainabilityPoints: 2615,
    rank: 5,
    level: 5,
  },
  {
    id: '6',
    name: 'Mario L.',
    username: '@mariol',
    avatar: 'https://i.pravatar.cc/150?img=15',
    sustainabilityPoints: 2587,
    rank: 6,
    level: 6,
  },
  {
    id: '7',
    name: 'Maddy B.',
    username: '@maddyb',
    avatar: 'https://i.pravatar.cc/150?img=10',
    sustainabilityPoints: 2450,
    rank: 7,
    level: 7,
  },
  {
    id: '8',
    name: 'Howard C.',
    username: '@howardc',
    avatar: 'https://i.pravatar.cc/150?img=14',
    sustainabilityPoints: 2333,
    rank: 8,
    level: 8,
  },
  {
    id: '9',
    name: 'Cole M.',
    username: '@colem',
    avatar: 'https://i.pravatar.cc/150?img=11',
    sustainabilityPoints: 2108,
    rank: 9,
    level: 9,
  },
  {
    id: '10',
    name: 'Anne F.',
    username: '@annef',
    avatar: 'https://i.pravatar.cc/150?img=9',
    sustainabilityPoints: 1775,
    rank: 10,
    level: 10,
  },
];

export const RANK_REWARDS: RankReward[] = [
  {
    minRank: 1,
    maxRank: 1,
    title: 'Hạng Nhất - Huyền Thoại',
    icon: '👑',
    color: '#FFD700',
    rewards: [
      {
        id: 'r1-1',
        type: 'points',
        name: '5000 Điểm Xanh',
        description: 'Phần thưởng đặc biệt cho Quán quân',
        icon: '💎',
        value: 5000,
      },
      {
        id: 'r1-2',
        type: 'voucher',
        name: 'Voucher 500.000đ',
        description: 'Mua sắm thời trang xanh tại GreenLoop',
        icon: '🎫',
        value: 500000,
      },
      {
        id: 'r1-3',
        type: 'badge',
        name: 'Huy Hiệu Vàng',
        description: 'Champion của tháng - Hiển thị trên hồ sơ',
        icon: '🏆',
      },
      {
        id: 'r1-4',
        type: 'coin',
        name: '1000 Xu Vàng',
        description: 'Dùng để mua items độc quyền trong app',
        icon: '🪙',
        value: 1000,
      },
      {
        id: 'r1-5',
        type: 'badge',
        name: 'Danh Hiệu "Eco Warrior"',
        description: 'Danh hiệu đặc biệt hiếm có',
        icon: '⚔️',
      },
    ],
  },
  {
    minRank: 2,
    maxRank: 3,
    title: 'Hạng 2-3 - Cao Thủ',
    icon: '🥈',
    color: '#C0C0C0',
    rewards: [
      {
        id: 'r2-1',
        type: 'points',
        name: '3000 Điểm Xanh',
        description: 'Phần thưởng cho Top 3',
        icon: '💎',
        value: 3000,
      },
      {
        id: 'r2-2',
        type: 'voucher',
        name: 'Voucher 300.000đ',
        description: 'Mua sắm thời trang xanh tại GreenLoop',
        icon: '🎫',
        value: 300000,
      },
      {
        id: 'r2-3',
        type: 'badge',
        name: 'Huy Hiệu Bạc',
        description: 'Top 3 xuất sắc - Hiển thị trên hồ sơ',
        icon: '🥈',
      },
      {
        id: 'r2-4',
        type: 'coin',
        name: '600 Xu Vàng',
        description: 'Dùng để mua items trong app',
        icon: '🪙',
        value: 600,
      },
      {
        id: 'r2-5',
        type: 'badge',
        name: 'Danh Hiệu "Green Master"',
        description: 'Bậc thầy về môi trường',
        icon: '🌟',
      },
    ],
  },
  {
    minRank: 4,
    maxRank: 10,
    title: 'Hạng 4-10 - Tinh Anh',
    icon: '🥉',
    color: '#CD7F32',
    rewards: [
      {
        id: 'r3-1',
        type: 'points',
        name: '1500 Điểm Xanh',
        description: 'Phần thưởng cho Top 10',
        icon: '💎',
        value: 1500,
      },
      {
        id: 'r3-2',
        type: 'voucher',
        name: 'Voucher 150.000đ',
        description: 'Mua sắm tại GreenLoop',
        icon: '🎫',
        value: 150000,
      },
      {
        id: 'r3-3',
        type: 'badge',
        name: 'Huy Hiệu Đồng',
        description: 'Top 10 tháng này',
        icon: '🥉',
      },
      {
        id: 'r3-4',
        type: 'coin',
        name: '300 Xu Vàng',
        description: 'Dùng để mua items trong app',
        icon: '🪙',
        value: 300,
      },
    ],
  },
  {
    minRank: 11,
    maxRank: 50,
    title: 'Hạng 11-50 - Chiến Binh Xanh',
    icon: '🌟',
    color: '#4CAF50',
    rewards: [
      {
        id: 'r4-1',
        type: 'points',
        name: '500 Điểm Xanh',
        description: 'Phần thưởng khích lệ',
        icon: '💎',
        value: 500,
      },
      {
        id: 'r4-2',
        type: 'voucher',
        name: 'Voucher 50.000đ',
        description: 'Giảm giá khi mua sắm',
        icon: '🎫',
        value: 50000,
      },
      {
        id: 'r4-3',
        type: 'badge',
        name: 'Huy Hiệu Xanh',
        description: 'Top 50 tháng này',
        icon: '🌿',
      },
      {
        id: 'r4-4',
        type: 'coin',
        name: '100 Xu Vàng',
        description: 'Dùng để mua items trong app',
        icon: '🪙',
        value: 100,
      },
    ],
  },
  {
    minRank: 51,
    maxRank: 100,
    title: 'Hạng 51-100 - Tân Binh',
    icon: '🎖️',
    color: '#8BC34A',
    rewards: [
      {
        id: 'r5-1',
        type: 'points',
        name: '200 Điểm Xanh',
        description: 'Tiếp tục phấn đấu!',
        icon: '💎',
        value: 200,
      },
      {
        id: 'r5-2',
        type: 'voucher',
        name: 'Voucher 20.000đ',
        description: 'Giảm giá khi mua sắm',
        icon: '🎫',
        value: 20000,
      },
      {
        id: 'r5-3',
        type: 'coin',
        name: '50 Xu Vàng',
        description: 'Dùng để mua items trong app',
        icon: '🪙',
        value: 50,
      },
    ],
  },
  {
    minRank: 101,
    maxRank: 999,
    title: 'Hạng 100+ - Người Chơi Mới',
    icon: '🌱',
    color: '#9E9E9E',
    rewards: [
      {
        id: 'r6-1',
        type: 'points',
        name: '50 Điểm Xanh',
        description: 'Phần thưởng tham gia',
        icon: '💎',
        value: 50,
      },
      {
        id: 'r6-2',
        type: 'coin',
        name: '20 Xu Vàng',
        description: 'Khởi đầu hành trình',
        icon: '🪙',
        value: 20,
      },
      {
        id: 'r6-3',
        type: 'badge',
        name: 'Huy Hiệu Tân Thủ',
        description: 'Chào mừng bạn đến GreenLoop',
        icon: '🌱',
      },
    ],
  },
];
