import { Product } from '@/types/product';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Áo thun Cotton Organic',
    description: 'Áo thun làm từ cotton hữu cơ 100%, thân thiện với môi trường',
    price: 299000,
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400',
    category: 'clothing',
    sustainability: 5,
    inStock: true,
    condition: 'new',
  },
  {
    id: '2',
    name: 'Túi Vải Tái Chế',
    description: 'Túi xách làm từ vải tái chế, bền đẹp và phong cách',
    price: 450000,
    image: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=400',
    category: 'bags',
    sustainability: 5,
    inStock: true,
    condition: 'new',
  },
  {
    id: '3',
    name: 'Giày Sneaker Eco',
    description: 'Giày thể thao làm từ vật liệu tái chế',
    price: 890000,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400',
    category: 'shoes',
    sustainability: 4,
    inStock: true,
    condition: 'like-new',
  },
  {
    id: '4',
    name: 'Áo Sơ Mi Linen',
    description: 'Áo sơ mi linen tự nhiên, thoáng mát',
    price: 550000,
    image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=400',
    category: 'clothing',
    sustainability: 5,
    inStock: true,
    condition: 'new',
  },
  {
    id: '5',
    name: 'Mũ Cói Thủ Công',
    description: 'Mũ cói được làm thủ công từ làng nghề truyền thống',
    price: 180000,
    image: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=400',
    category: 'accessories',
    sustainability: 5,
    inStock: true,
    condition: 'new',
  },
  {
    id: '6',
    name: 'Quần Jeans Tái Chế',
    description: 'Quần jeans được làm từ vải denim tái chế',
    price: 680000,
    image: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=400',
    category: 'clothing',
    sustainability: 4,
    inStock: false,
    condition: 'good',
  },
];

export const CATEGORIES = [
  { id: 'all', name: 'Tất cả', icon: '🌿' },
  { id: 'clothing', name: 'Quần áo', icon: '👕' },
  { id: 'accessories', name: 'Phụ kiện', icon: '👒' },
  { id: 'shoes', name: 'Giày dép', icon: '👟' },
  { id: 'bags', name: 'Túi xách', icon: '👜' },
];